# -*- coding: utf-8 -*-
"""Nuevoo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lZjzGC5fI7VGu9lvbG55NgTTyDruq-r
"""

import streamlit as st

# Configuración de la página
st.set_page_config(page_title="Econofy - Calculadoras Financieras", page_icon="💰")
st.title("💰 Econofy - Calculadoras Financieras Inteligentes")

# --- Calculadora de ahorro mensual ---
st.header("Calculadora de ahorro mensual")
monto_mensual = st.number_input("Monto a ahorrar por mes (₡):", min_value=0.0, step=1000.0, format="%.2f", key="monto_ahorro")
meses_ahorro = st.number_input("Cantidad de meses:", min_value=1, step=1, key="meses_ahorro")

if st.button("Calcular ahorro total"):
    total_ahorro = monto_mensual * meses_ahorro
    st.success(f"En {meses_ahorro} meses ahorrarás ₡{total_ahorro:,.2f}")

    if monto_mensual == 0:
        st.info("Considera aumentar tu monto mensual para mejorar tus ahorros.")
    elif total_ahorro < 50000:
        st.info("Intenta ahorrar un poco más para tener un fondo de emergencia sólido.")
    else:
        st.info("¡Buen trabajo! Estás encaminado a tus metas financieras.")

# --- Calculadora de pago mensual de deuda ---
st.header("Calculadora de pago mensual de deuda")
deuda = st.number_input("Monto de la deuda (₡):", min_value=0.0, step=1000.0, format="%.2f", key="monto_deuda")
plazo_deuda = st.number_input("Meses para pagar la deuda:", min_value=1, step=1, key="plazo_deuda")

if st.button("Calcular cuota mensual"):
    if plazo_deuda > 0: # Evitar división por cero
        cuota = deuda / plazo_deuda
        st.success(f"Deberás pagar ₡{cuota:,.2f} cada mes durante {plazo_deuda} meses.")

        # Comparación con el monto de ahorro mensual (si se ha ingresado)
        if monto_mensual > 0 and cuota > monto_mensual:
            st.warning("La cuota mensual de la deuda es mayor que tu monto de ahorro mensual. Considera ajustar tus finanzas.")
        elif monto_mensual > 0:
            st.info("El plan de pago parece viable con tu ahorro mensual.")
    else:
        st.warning("El plazo para pagar la deuda debe ser al menos 1 mes.")

# --- Consejos generales ---
st.markdown("---")
st.subheader("Consejos financieros")

# Consejos basados en la deuda
if deuda > 0:
    st.write("- Prioriza pagar deudas con altas tasas de interés.")
else:
    st.write("- Si no tienes deudas, sigue ahorrando y considera invertir.")

# Consejos basados en el ahorro
if monto_mensual > 0 and meses_ahorro > 0:
    st.write("- Mantén la constancia en tu ahorro mensual para alcanzar tus metas.")
else:
    st.write("- Define un plan de ahorro mensual para mejorar tu salud financiera.")

# Nota: Se agregaron "key" a los st.number_input para evitar advertencias de Streamlit
# cuando hay múltiples widgets del mismo tipo sin una clave única.